# Generated by Django 6.0.7 on 2026-08-27 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('trust_score', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted_label', models.CharField(choices=[('fake', 'Fake'), ('genuine', 'Genuine')], max_length=10)),
                ('confidence', models.FloatField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('similarity_flag', models.CharField(blank=True, max_length=50)),
                ('top_words', models.CharField(blank=True, max_length=500)),
                ('reasons', models.TextField(blank=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_label', models.CharField(blank=True, choices=[('fake', 'Fake'), ('genuine', 'Genuine')], max_length=10, null=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.product')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.reviewer')),
            ],
        ),
    ]
